name: Test CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Find version number
      id: flowbuild
      run: | 
        export SOME_VERSION=$(python --version)
        echo "::set-output name=ver::${SOME_VERSION}"
      
    - name: Push to dockerhub
      run: echo "georgegach/flowiz:${{ steps.flowbuild.outputs.ver }}"
    
